steps:
  - command: echo 'First Stage'
    label: ':hammer:'
  - wait
  - trigger: dependent-pipeline-example-deploy
    key: "deploy"
    label: ":rocket:"
    branches: "master"
    async: false
    build:
      commit: "$BUILDKITE_COMMIT"
      branch: "$BUILDKITE_BRANCH"
      message: "$BUILDKITE_MESSAGE"

  - block: ":rocket: PROD Release!"
    prompt: You are about to create a new release. This cannot be undone.
    fields:
      - select: "Release type"
        key: "release_type"
        multiple: false
        options:
          - label: "Patch"
            value: "Patch"
          - label: "Minor"
            value: "Minor"
          - label: "Major"
            value: "Major"
          - label: "None (What are you doing here then?)"
            value: "None"
  - wait: ~

  - wait: ~

  - label: "Triggering primarily pipeline to build and release"
    #if: "build.env('release_type') != 'None'"
    command: |
      if [ "$(buildkite-agent meta-data get release_type)" == "Patch" ]; then
         chmod 777 .buildkite/scripts/approval.sh
         .buildkite/scripts/approval.sh
      fi