steps:
  - command: echo 'First Stage'
    label: ':hammer:'
  - wait
  - trigger: dependent-pipeline-example-deploy
    key: "deploy"
    label: ":rocket:"
    branches: "master"
    async: false
    build:
      commit: "$BUILDKITE_COMMIT"
      branch: "$BUILDKITE_BRANCH"
      message: "$BUILDKITE_MESSAGE"
  - block: "Approval: yes or no"
    fields:
      - select: "Approval stage"
        key: "approval-stage"
        hint: "Major and minor versions should only be incremented as discussed with your Delivery Lead :fork:"
        required: true
        options:
          - label: "Yes"
            value: "yes"
          - label: "No"
            value: "no"
  - command: `../scripts/script.sh`
    key: "$(bash 'require("../scripts/script.sh").init("${APPROVAL_RESPONSE}")')"
  - command: echo 'Last Stage'
    key: "last"
    label: ':hammer:'
    depends_on: "approval-stage"
