steps:
  - command: echo 'First Stage'
    label: ':hammer:'
  - wait
  - trigger: dependent-pipeline-example-deploy
    key: "deploy"
    label: ":rocket:"
    branches: "master"
    async: false
    build:
      commit: "$BUILDKITE_COMMIT"
      branch: "$BUILDKITE_BRANCH"
      message: "$BUILDKITE_MESSAGE"

  - block: ":rocket: PROD Release!"
    prompt: You are about to create a new release. This cannot be undone.
    fields:
      - select: "Release type"
        key: "approval-stage"
        multiple: false
        options:
          - label: "Yes"
            value: "yes"
          - label: "No"
            value: "no"

  - wait: ~

  - label: "Triggering primarily pipeline to build and release"
    key: "next_file"
    command: |
      if [ "$(buildkite-agent meta-data get approval-stage)" == "yes" ]; then
         # chmod 777 .buildkite/scripts/approval.sh
         # .buildkite/scripts/approval.sh
         chmod 777 .buildkite/pipeline1.yml
         buildkite-agent pipeline upload pipeline1.yml
      else
        echo "GoodBye"
      fi