steps:
  - command: |
      echo 'First Stage'
      # curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' https://hooks.slack.com/services/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
      npm install @slack/webhook
      #node .buildkite/slack.js
    label: ':hammer:'
    key: "First"
  - wait
  - block: ":rocket: Approval Release!"
    depends_on: "First"
    key: "Second"
    prompt: Select Yes or No to deploy Murray Env.
    fields:
      - select: "Approval Stage"
        required: true
        default: "yes"
        key: "approval_stage"
        multiple: false
        options:
          - label: "Yes"
            value: "yes"
          - label: "No"
            value: "no"

  - label: "Triggering Pipeline2 : Yes  or No"
    key: "next_file"
    depends_on: "Second"
    command: |
      if [ "$( buildkite-agent meta-data get approval-stage )" == "yes" ]; then
        buildkite-agent pipeline upload .buildkite/pipeline1.yml
      else
        echo "GoodBye"
      fi
