steps:
  - command: echo 'First Stage'
    label: ':hammer:'
    key: "First"
  - wait
  - block: ":rocket: PROD Release!"
    depends_on: "First"
    key: "Second"
    prompt: You are about to create a new release. This cannot be undone.
    fields:
      - select: "Release type"
        key: "approval_stage"
        multiple: false
        options:
          - label: "Yes"
            value: "yes"
          - label: "No"
            value: "no"

  - wait: ~
  - label: "Load release type into env variable"
    command: |
      export approval_stage=$(buildkite-agent meta-data get approval_stage)
      echo "Demo $approval_stage"
  
  - wait: ~

  - label: "Triggering primarily pipeline to build and release"
    if: "build.env('approval_stage') == 'yes'"
    command: |
      echo Building release of $approval_stage

  - label: "Triggering primarily pipeline to build and release"
    key: "next_file"
    depends_on: "Second"
    command: |
      if [ "$(buildkite-agent meta-data get approval_stage)" == "yes" ]; then
         node demo.js
      else
        echo "GoodBye"
      fi