steps:
  - command: echo 'First Stage'
    label: ':hammer:'
  - wait
  - trigger: dependent-pipeline-example-deploy
    key: "deploy"
    label: ":rocket:"
    branches: "master"
    async: false
    build:
      commit: "$BUILDKITE_COMMIT"
      branch: "$BUILDKITE_BRANCH"
      message: "$BUILDKITE_MESSAGE"
  - block: "Approval: yes or no"
    fields:
      - select: "Approval stage"
        key: "approval-stage"
        hint: "Major and minor versions should only be incremented as discussed with your Delivery Lead :fork:"
        required: true
        options:
          - label: "Yes"
            value: "yes"
          - label: "No"
            value: "no"
  - wait: ~
  
  - label: "Load release type into env variable"
    command: |
      export APPROVAL_RESPONSE="$(buildkite-agent meta-data get "approval-stage")"
  
  - wait: ~

  - label: "Triggering primarily pipeline to build and release"
    if: "build.env('APPROVAL_RESPONSE') == 'yes'"
    command: |
      echo Building release of "$APPROVAL_RESPONSE"

  - label: "Cancelled release"
    if: "build.env('APPROVAL_RESPONSE') == 'no'"
    command: echo Cancelled release
#   - label: ":rocket:  inline sh"
#     command: |
#       set -eo pipefail
#       APPROVAL_RESPONSE=$(buildkite-agent meta-data get approval-stage)
#       echo $APPROVAL_RESPONSE
#       export APPROVAL_RESPONSE

  - command: '.buildkite/scripts/approval.sh'
    label: ":hammer: echo"
